language: go

go:
  - 1.9
  - master 

install: true

sudo: false

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

before_script:
  - go get github.com/golang/lint/golint                        # Linter
  - go get github.com/fzipp/gocyclo
  - go get github.com/nebulouslabs/go-upnp
  - go get github.com/tatsushid/go-fastping
  - go get github.com/twitchtv/twirp
  - go get golang.org/x/crypto/sha3

script:
  - test -z $(gofmt -s -l .)  # Fail if a .go file hasn't been formatted with gofmt
  - go vet ./...                      # go vet is the official Go static analyzer
